### ISSUE TITLE
Problems with the installation

### ISSUE THREAD

**Issue by gudlot** [LennardKrause/xrdPlanner#1]
Hi,
I created a new environment with Python 3.11.9.
I cloned the repo.
I ran `pip install -e .`

I got:
```
Obtaining file:.../xrdPlanner
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [98 lines of output]
      No `packages` or `py_modules` configuration, performing automatic discovery.
      `flat-layout` detected -- analysing .
      discovered packages -- ['settings', 'icons', 'xrdPlanner', 'xrdPlanner.settings']
      Traceback (most recent call last):
        File "/Users/user/miniforge3/envs/xrdplanner/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/user/miniforge3/envs/xrdplanner/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/user/miniforge3/envs/xrdplanner/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 464, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 158, in setup
          dist.parse_config_files()
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 608, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 71, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 143, in read_configuration
          return expand_configuration(asdict, root_dir, ignore_option_errors, dist)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 168, in expand_configuration
          return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 216, in expand
          self._expand_all_dynamic(dist, package_dir)
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 261, in _expand_all_dynamic
          version=self._obtain_version(dist, package_dir),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 312, in _obtain_version
          self._obtain(dist, "version", package_dir)  # pyright: ignore[reportArgumentType]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 299, in _obtain
          return self._expand_directive(
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 293, in _expand_directive
          return _expand.read_attr(directive["attr"], package_dir, root_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 179, in read_attr
          path = _find_module(module_name, package_dir, root_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 225, in _find_module
          path_start = find_package_path(module_name, package_dir or {}, root_dir)
                                                      ^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 440, in __len__
          return len(self._target())
                     ^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 433, in _target
          self._value = self._obtain()
                        ^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 403, in _get_package_dir
          self()
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 388, in __call__
          self._dist.set_defaults(name=False)  # Skip name, we can still be parsing
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/discovery.py", line 346, in __call__
          self._analyse_package_layout(ignore_ext_modules)
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/discovery.py", line 380, in _analyse_package_layout
          or self._analyse_flat_layout()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/discovery.py", line 437, in _analyse_flat_layout
          return self._analyse_flat_packages() or self._analyse_flat_modules()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/discovery.py", line 443, in _analyse_flat_packages
          self._ensure_no_accidental_inclusion(top_level, "packages")
        File "/private/var/folders/gt/zdhpt1nn57l6r7yz21_l2nwc0000gp/T/pip-build-env-n7ii4bk0/overlay/lib/python3.11/site-packages/setuptools/discovery.py", line 473, in _ensure_no_accidental_inclusion
          raise PackageDiscoveryError(cleandoc(msg))
      setuptools.errors.PackageDiscoveryError: Multiple top-level packages discovered in a flat-layout: ['icons', 'settings', 'xrdPlanner'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I don't know if this is my fault, but I thought I mention it.
I solved the problem for me by manual installation of the required packages. I ran `xrdPlanner` from a Jupyter notebook via main.

**Comment by gudlot** [comment]
A fix for this issue is to explicitly specify which packages to include in the `pyproject.toml`.

Add the following section at the bottom of your `pyproject.toml`:

```toml
[tool.setuptools.packages.find]
include = ["xrdPlanner", "icons", "settings"]
```

After adding this, the installation using editable mode works:

`pip install -e .`
